import type { Metadata } from "next";
import { Rethink_Sans, Inter, Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const rethink = Rethink_Sans({
  subsets: ["latin"],
  variable: "--font-rethink",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

const arial = localFont({
  src: "./fonts/arial.ttf",
  variable: "--font-arial",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Eagle Likes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${rethink.variable} ${inter.variable} ${arial.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
